name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  SERVICES: "user-service auth-service video-service watch-history-service"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push images
        run: |
          set -euo pipefail
          for SVC in $SERVICES; do
            CONTEXT=services/$SVC
            if [ -f "$CONTEXT/Dockerfile" ]; then
              IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/$SVC:$(echo $GITHUB_SHA | cut -c1-7)
              docker build -t $IMAGE $CONTEXT
              docker push $IMAGE
              echo "Built and pushed $IMAGE"
            else
              echo "No Dockerfile for $SVC, skipping"
            fi
          done

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ArgoCD CLI
        uses: clowdhaus/argo-cd-action@v2
        with:
          version: v2.10.7

      - name: Sync App(s)
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          argocd login "$ARGOCD_SERVER" --username "$ARGOCD_USERNAME" --password "$ARGOCD_PASSWORD" --insecure
          argocd app sync self-healing-root --timeout 600
